/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.gui;

import com.mysql.jdbc.Util;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import project.dao.Product_purchase;
import project.dao.PurchaseDao;
import project.model.Product;
import project.model.PurchaseProduct;
import project.util.DataUtil;
import project.util.DatabaseUtil;

/**
 *
 * @author Mnselim
 */
public class Order extends javax.swing.JFrame {
    
    private DataUtil util = new DataUtil();
    ResultSetModel rsm = new ResultSetModel();
    
    private ArrayList<PurchaseProduct> pProduct = new ArrayList<PurchaseProduct>();
    private DefaultTableModel productPerchaseDetailsTableModel;
    
    /**
     * Creates new form Order
     */
    public Order() {
        
        initComponents();
        combo();
        combobox();
    }
   
    
      public void combobox(){
        String sql="SELECT * FROM product";
        try {
            ResultSet rs = util.select(sql);
            while(rs.next()){
                String name =rs.getString("name");
                comboProduct.addItem(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void combo(){
    String sql="SELECT * FROM dealer";
        try {
            ResultSet rs = util.select(sql);
            while(rs.next()){
                String name=rs.getString("name");
                comboDealer.addItem(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        gfh = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboProduct = new javax.swing.JComboBox<>();
        txtUniteprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProductprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSubmitAmount = new javax.swing.JTextField();
        txtDue = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        comboDealer = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtdueamount = new javax.swing.JTextField();
        dateChoser = new com.toedter.calendar.JDateChooser();
        txtPurchaseId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtdealerId = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnTotalPrice = new javax.swing.JButton();
        btnconfirmSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductParchase = new javax.swing.JTable();
        btnExist1 = new javax.swing.JToggleButton();
        btnHomeb = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gfh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Sagor Bakery ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Product");

        comboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        comboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductActionPerformed(evt);
            }
        });

        txtUniteprice.setEnabled(false);
        txtUniteprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitepriceActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Unite price");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Quantity");

        txtProductprice.setEnabled(false);
        txtProductprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductpriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Product Price");

        btnNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNew.setText("Add product");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtUniteprice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtProductprice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnNew)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(txtUniteprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        txtTotalPrice.setEditable(false);
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total price");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Submit anount");

        txtDue.setEditable(false);
        txtDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Today Due");

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comboDealer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        comboDealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDealerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Dealer ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Date");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText(" Due amount");

        txtdueamount.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Purchase Id");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Id");

        txtdealerId.setEnabled(false);
        txtdealerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdealerIdActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(comboDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdealerId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdueamount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel11))
                    .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPurchaseId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnFind)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPurchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFind)
                                .addComponent(btnClear))
                            .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdueamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdealerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTotalPrice.setText("Total Price");
        btnTotalPrice.setToolTipText("");
        btnTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPriceActionPerformed(evt);
            }
        });

        btnconfirmSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnconfirmSubmit.setText(" confirm Submit");
        btnconfirmSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmSubmitActionPerformed(evt);
            }
        });

        tblProductParchase.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblProductParchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Unite Price", "Quantity", "Product Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductParchase);

        btnExist1.setBackground(new java.awt.Color(204, 0, 0));
        btnExist1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExist1.setText("Exist");
        btnExist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExist1ActionPerformed(evt);
            }
        });

        btnHomeb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHomeb.setText("Home");
        btnHomeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gfhLayout = new javax.swing.GroupLayout(gfh);
        gfh.setLayout(gfhLayout);
        gfhLayout.setHorizontalGroup(
            gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gfhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gfhLayout.createSequentialGroup()
                        .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gfhLayout.createSequentialGroup()
                                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gfhLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExist1)
                                    .addComponent(btnHomeb))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gfhLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gfhLayout.createSequentialGroup()
                                .addComponent(btnHome)
                                .addGap(59, 59, 59))
                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gfhLayout.createSequentialGroup()
                                .addComponent(btnTotalPrice)
                                .addGap(18, 18, 18)
                                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSubmitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(btnconfirmSubmit)
                                .addGap(18, 18, 18)
                                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(gfhLayout.createSequentialGroup()
                                        .addComponent(txtDue, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSave)))
                                .addGap(145, 145, 145))))))
        );
        gfhLayout.setVerticalGroup(
            gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gfhLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(gfhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubmitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconfirmSubmit)
                    .addComponent(txtDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(btnTotalPrice))
                .addGap(18, 18, 18)
                .addComponent(btnHomeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExist1)
                .addGap(1905, 1905, 1905)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gfh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gfh, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnitepriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitepriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitepriceActionPerformed

    private void txtDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        
        
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void comboDealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDealerActionPerformed
        String tmp = (String) comboDealer.getSelectedItem();
        String sql = "SELECT * FROM dealer WHERE name=?";
        try {
             util.preaperStatement(sql);
             util.ps.setString(1, tmp);
             ResultSet rs = util.ps.executeQuery();
             
             while(rs.next()){
                 String add1 = rs.getString("due_balance");
                 txtdueamount.setText(add1);
                 String add2 = rs.getString("dealer_id");
                 txtdealerId.setText(add2);
                 
                 
                 
             }
        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
     
         PurchaseDao pdao = new PurchaseDao();
        try {
            int id = pdao.maxId();
            txtPurchaseId.setText(id+"");
        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboDealerActionPerformed

    private void comboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductActionPerformed
            String tmp = (String) comboProduct.getSelectedItem();
            String sql="SELECT * FROM product WHERE name=?";
        try {
            
            util.preaperStatement(sql);
            util.ps.setString(1, tmp);
            ResultSet rs=util.ps.executeQuery();
            
            while(rs.next()){
                String add = rs.getString("unite_orice");
                txtUniteprice.setText(add);
                
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboProductActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtProductpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductpriceActionPerformed
        //gjghli
    }//GEN-LAST:event_txtProductpriceActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
        String productName = comboProduct.getSelectedItem().toString();
        float unitPrice = Float.parseFloat(txtUniteprice.getText());
        int quentity = Integer.parseInt(txtQuantity.getText());
        float productPrice = Float.parseFloat(txtProductprice.getText());
        
        PurchaseProduct product = new PurchaseProduct();
        
        product.setProduct_name(productName);
        product.setUnite_price(unitPrice);
        product.setQuantity(quentity);
        product.setProduct_price(productPrice);
        
        pProduct.add(product);
        
        if(pProduct.size() != 1){
            // this code for clear jtable data
            productPerchaseDetailsTableModel.setRowCount(0);
        }
        
        productPerchaseDetailsTableModel = (DefaultTableModel) tblProductParchase.getModel();
        for(int i = 0;i<pProduct.size();i++){
            productPerchaseDetailsTableModel.addRow(
                    new Object[]{
                        pProduct.get(i).getProduct_name(),
                        pProduct.get(i).getUnite_price(),
                        pProduct.get(i).getQuantity(),
                        pProduct.get(i).getProduct_price()
                    }
            );
        }

            comboProduct.setSelectedItem("");
            txtUniteprice.setText("");
            txtQuantity.setText("");
            txtProductprice.setText("");
        
        
        
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPriceActionPerformed
        // TODO add your handling code here:
        
        float totalPrice = 0;
        for(int i = 0; i< pProduct.size(); i++){
            totalPrice += pProduct.get(i).getProduct_price();
        }
        
        txtTotalPrice.setText(String.valueOf(totalPrice));
        
    }//GEN-LAST:event_btnTotalPriceActionPerformed

    private void btnExist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExist1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExist1ActionPerformed

    private void btnHomebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomebActionPerformed
        HomeGui hgui = new HomeGui();
        hgui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomebActionPerformed

    private void btnconfirmSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmSubmitActionPerformed
        float total_price = Float.parseFloat(txtTotalPrice.getText());
        float submit_amount = Float.parseFloat(txtSubmitAmount.getText());
        float due_amount = (total_price-submit_amount);
        txtDue.setText(String.valueOf(due_amount));
    }//GEN-LAST:event_btnconfirmSubmitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        
        //String dealerName = comboDealer.getSelectedItem().toString();
        int dealer_id = Integer.parseInt(txtdealerId.getText());
        int purchase_id = Integer.parseInt(txtPurchaseId.getText());
       
        
       
        float today_due = Float.parseFloat(txtDue.getText());
        float total_price = Float.parseFloat(txtTotalPrice.getText());
        float submit_amount = Float.parseFloat(txtSubmitAmount.getText());
        
        
       // System.out.println(Date_Format.format(dateChoser.getDate()));
        String sql = "INSERT INTO purchase VALUES (?,?,?,?,?,?)";
//        String sql = "INSERT INTO `purchase`(`purchase_date`, `total_balance`, `submit_balance`, `due_balance`, `dealer_id`) VALUES (?, ?, ?, ?, ?)";
        
        String date = ((JTextField)dateChoser.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
        String formateDate = Date_Format.format(dateChoser.getDate());
        
        
        
        
        Connection con = DatabaseUtil.getConnection();
        
        try {
        
            con.setAutoCommit(false); // start transaction from here
            
            util.preaperStatement(sql);
            util.ps.setString(1,String.valueOf(purchase_id) );
            util.ps.setString(2,formateDate);
            util.ps.setString(3,String.valueOf(total_price));
            util.ps.setString(4, String.valueOf(submit_amount));
            util.ps.setString(5, String.valueOf(today_due));
            util.ps.setString(6, String.valueOf(dealer_id));
            util.ps.executeUpdate();
            util.ps.close();
            
            
            for(int i = 0;i < pProduct.size();i++){
                String sql2="INSERT INTO product_purchase(purchase_id,product_name,quantity,total_price,unite_price) VALUES (?,?,?,?,?)";
                util.preaperStatement(sql2);
                util.ps.setString(1, String.valueOf(txtPurchaseId.getText()));
                util.ps.setString(2, pProduct.get(i).getProduct_name());
                util.ps.setFloat(3, pProduct.get(i).getQuantity());
                util.ps.setFloat(4, pProduct.get(i).getProduct_price());
                util.ps.setFloat(5, pProduct.get(i).getUnite_price());
                util.ps.executeUpdate();
                util.ps.close();
            }
        
            con.commit(); // end transaction here
//            System.out.println(ppId);
            JOptionPane.showMessageDialog(null, "Purchased Successful!");
        } catch (SQLException ex) {
            //System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
       
        
        
        int deuAmmount = Integer.parseInt(txtdueamount.getText());
        float deu = Float.parseFloat(txtDue.getText());
        
        float totalDeu = deu + deuAmmount;
        
        txtdueamount.setText(String.valueOf(totalDeu));
        
        String update="UPDATE dealer SET due_balance="+totalDeu+" WHERE dealer_id=1";
        try {
            util.DML(update);
            
            } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtdealerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdealerIdActionPerformed
       
    }//GEN-LAST:event_txtdealerIdActionPerformed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        int quantity = Integer.parseInt(txtQuantity.getText());
        float price = Float.parseFloat(txtUniteprice.getText());
        float result = quantity*price;
        txtProductprice.setText (String.valueOf(result));
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        
        Product_purchase pp = new Product_purchase();
        pp.findPP(Integer.parseInt(txtPurchaseId.getText()));
//        pp.findPP(2);
        comboDealer.setSelectedItem(pp.getDealer().getName());
        txtdealerId.setText(String.valueOf(pp.getDealer().getDealer_id()));
        txtdueamount.setText(String.valueOf(pp.getDealer().getDue_balance()));
        
        dateChoser.setDate(pp.getPurchase().getDate());
        
        txtTotalPrice.setText(String.valueOf(pp.getPurchase().getTotal_price()));
        txtSubmitAmount.setText(String.valueOf(pp.getPurchase().getSubmite_amount()));
        txtDue.setText(String.valueOf(pp.getPurchase().getTotal_price() - pp.getPurchase().getSubmite_amount()));
        
        
        ArrayList<PurchaseProduct> productPurchase = pp.getPp();
        productPerchaseDetailsTableModel = (DefaultTableModel) tblProductParchase.getModel();
        
        if(pProduct.size() != 1){
            productPerchaseDetailsTableModel.setRowCount(0);
        }
        
        for (int i = 0; i < productPurchase.size(); i++) {
            productPerchaseDetailsTableModel.addRow(
                    new Object[]{
                        productPurchase.get(i).getProduct_name(),
                        productPurchase.get(i).getUnite_price(),
                        productPurchase.get(i).getQuantity(),
                        productPurchase.get(i).getProduct_price()
                    }
            );
        }
        txtPurchaseId.setText(String.valueOf(pp.getPurchase().getPurchase_id()));
        btnNew.setEnabled(false);
        btnTotalPrice.setEnabled(false);
        btnSave.setEnabled(false);
        btnconfirmSubmit.setEnabled(false);
        comboDealer.setEnabled(false);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtPurchaseId.setText("");
        txtdealerId.setText("");
        comboDealer.setSelectedItem("");
        comboProduct.setSelectedItem("");
        txtdueamount.setText("");
        txtDue.setText("");
        dateChoser.setDate(null);
        txtUniteprice.setText("");
        txtQuantity.setText("");
        txtProductprice.setText("");
        txtTotalPrice.setText("");
        txtSubmitAmount.setText("");
        txtDue.setText("");
        btnNew.setEnabled(true);
        btnTotalPrice.setEnabled(true);
        btnSave.setEnabled(true);
        btnconfirmSubmit.setEnabled(true);
        comboDealer.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JToggleButton btnExist1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHomeb;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTotalPrice;
    private javax.swing.JButton btnconfirmSubmit;
    private javax.swing.JComboBox<String> comboDealer;
    private javax.swing.JComboBox<String> comboProduct;
    private com.toedter.calendar.JDateChooser dateChoser;
    private javax.swing.JPanel gfh;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductParchase;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtProductprice;
    private javax.swing.JTextField txtPurchaseId;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubmitAmount;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtUniteprice;
    private javax.swing.JTextField txtdealerId;
    private javax.swing.JTextField txtdueamount;
    // End of variables declaration//GEN-END:variables
}
